# Paso 3 Dockerizing our app 
# Dockerfile.dev

FROM node:16-alpine

WORKDIR /app
# COPY . /app

COPY package.json ./

# COPY yarn.lock ./
# # la siguiente la agrego para no instalar en yarn en el proyecto dev 
# RUN npm install -g yarn 

# RUN yarn install --frozen-lockfile

COPY package-lock.json ./ 
# Asegúrate de incluir package-lock.json si está presente
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install





COPY . .




