FROM node:16-alpine AS build
WORKDIR /app

COPY package.json ./

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install

COPY . .

RUN npm run build


#STEP 2 CREATE NGINX SERVER
# FROM nginx:1.19.0-alpine AS prod-stage
# COPY --from=build /app/build /usr/share/nginx/html
# expose 80
# CMD ["nginx","-g","daemon off;"]