FROM node:16-alpine AS builder
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./ 
# COPY yarn.lock ./
ENV PATH /app/node_modules/.bin:$PATH
# RUN yarn install --frozen-lockfile
RUN npm install

COPY . .

# RUN npm run build
