# Paso 4a Docker Compose
# Paso 5 Docker build.
# ejecutar en el cli la siguiente linea
# docker-compose -f docker-compose.dev.yml up -d --build
version: "3"

services:

  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: react_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    command: >
      # sh -c "yarn start"
      sh -c "npm run startDev"

    env_file:
      - .env
